[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "libversion"
version = "file:VERSION"
description = "A version-aware utility library for REMLA project"
dependencies = []
