name: Release lib-version

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+(-[a-zA-Z0-9]+)?' # Only run this workflow when a tag like 1.2.3, 1.2.3-alpha, 1.2.3-beta is pushed

jobs:
  release:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install build tool
        run: pip install build

      - name: Build the Python package
        run: python -m build

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: libversion-${{ github.ref_name }}
          path: dist/