name: Release lib-version

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Only run this workflow when a tag like v1.0.0 is pushed

jobs:
  release:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Parse version info from tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install build tool
        run: pip install build

      - name: Set version in VERSION file
        run: echo "${{ env.version }}" > VERSION

      - name: Build the Python package
        run: python -m build

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: libversion-${{ env.version }}
          path: dist/
